#!/bin/bash

set -eu
set -o pipefail
set -x

main() {
  local platform=${SYNCSTORAGE_PLATFORMS:-local}
  local dir

  dir=$(./download-syncstorage-rs)

  cd "$dir"

  docker build --build-arg DATABASE_BACKEND=mysql --label tommie/syncstorage-rs --platform "$platform" --pull .
}

main "$@"
